version: '3.8'

services:
  postgres:
    container_name: library-management
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library_management
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
